global:
  resolve_timeout: 5m

route:
  group_by: [ "alertname" ]
  group_wait: 30s # default = 30s
  group_interval: 5m # default = 5m
  repeat_interval: 1h # default = 4h
  receiver: default-receiver
  routes:
    - receiver: kusama-GER
      match_re:
        job: kusama-validator01|kusama-validator02
    - receiver: kusama2-GER
      match_re:
        job: kusama-validator04|kusama-validator05
    - receiver: kusama3-GER
      match_re:
        job: kusama-validator09|polkadot-validator01
    - receiver: kusama4-GER
      match_re:
        job: kusama-validator03|kusama-validator06
    - receiver: kusama5-GER
      match_re:
        job: kusama-validator07|kusama-validator08
    - receiver: kusama6-GER
      match_re:
          job: kusama-validator10|kusama-validator11

receivers:
  - name: default-receiver
    webhook_configs:
      - url: http://127.0.0.1:8080/webhook
  - name: kusama-GER
    webhook_configs:
      - url: http://172.25.251.231:8080/webhook
  - name: kusama2-GER
    webhook_configs:
      - url: http://172.25.251.232:8080/webhook
  - name: kusama3-GER
    webhook_configs:
      - url: http://172.25.251.233:8080/webhook
  - name: kusama4-GER
    webhook_configs:
      - url: http://172.25.251.235:8080/webhook
  - name: kusama5-GER
    webhook_configs:
      - url: http://172.25.251.236:8080/webhook
  - name: kusama6-GER
    webhook_configs:
      - url: http://172.25.251.237:8080/webhook
