global:
  resolve_timeout: 5m
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: smtp.163.com:25 # smtp.gmail.com:587
  smtp_from: tailin_zhang@163.com
  smtp_auth_username: tailin_zhang@163.com
  smtp_auth_password: password
  smtp_require_tls: false

route:
  group_by: ["alertname"]
  group_wait: 1m
  group_interval: 30s
  repeat_interval: 5m
  receiver: devops

receivers:
  - name: devops
    email_configs:
      - to: "tailin_zhang@qq.com"
        headers: { Subject: "测试环境-告警邮件"}
        send_resolved: true
