groups:
  - name: polkadot.rules
    rules:

      ##############################################################################
      # Networking
      ##############################################################################

      - alert: NumberOfPeersLow
        expr: polkadot_sub_libp2p_peers_count < 3
        for: 3m
        labels:
          severity: warning
        annotations:
          message: 'The node {{ $labels.instance }} has less than 3 peers for more
      than 3 minutes'
      - alert: NumberOfPeersLow
        expr: polkadot_sub_libp2p_peers_count < 3
        for: 15m
        labels:
          severity: critical
        annotations:
          instance: "{{ $labels.job }}"
          description: 'The node {{ $labels.instance }} has less than 3 peers for more
      than 15 minutes'
      - alert: NoIncomingConnection
        expr: increase(polkadot_sub_libp2p_incoming_connections_total[20m]) == 0
        labels:
          severity: warning
        annotations:
          instance: "{{ $labels.job }}"
          description: 'The node {{ $labels.instance }} has not received any new incoming
      TCP connection in the past 20 minutes. Is it connected to the Internet?'
