groups:
  - name: alive.rules
    rules:
      - alert: 哎呀，您有个节点挂了
        expr: up == 0
        for: 15s
        labels:
          severity: error
        annotations:
          summary: "{{ $labels.instance }} 机器上的有节点宕机了"
          instance: "{{ $labels.job }}"
          description: "{{ $labels.instance }} 机器上的 {{ $labels.job }} 节点已经挂了超过15秒了，请快去检查下！"
