groups:
  - name: alive.rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          severity: error
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          instance: "{{ $labels.job }}"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."
